obj-m:=Chardriver.o
KDIR=/lib/modules/$(shell uname -r)/build/
PWD=$(shell pwd)

default:
	$(MAKE) -C $(KDIR) M=$(PWD) modules
	gcc -o Application Application.c
clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	rm Application

install:
	$(MAKE) -C $(KDIR) M=$(PWD)
